### ISSUE TITLE
Feature suggestion: allow non-numerical footnotes

### ISSUE THREAD

**Issue by pchr8** [akaalias/obsidian-footnotes#11]
Firstly, thank you for an excellent plugin, not being able to do footnotes easily added a lot of friction for me, now this is fixed!

I previously edited my markdown in vim, and had a mapping that does basically the same thing as this plugin, but takes the word under the cursor as footnote id.

For example:
```
This is some text and this is my source footnotesource.
```

If I put my cursor on "footnotesource", it would change this to 

```
This is some text and this is my source [^footnotesource].

[^footnotesource]: <cursor>
```

My main use case for this - I often edit separate markdown files that then get merged into a big one, and all the footnotes shouldn't get mixed up, same for copypasting snippets. Another way to solve this would be to randomize the footnotes, though this would hurt readability. 

I'd gladly help with this if this is needed by at least some other people, this issue is also a way to gauge interest in that

SH

**Comment by Comprehensive-Jason** [comment]
I am a maintainer for [MichaBrugger's Obsidian Footnotes](https://github.com/MichaBrugger/obsidian-footnotes) plugin, an active fork of this plugin.
The ability to work with non-numerical footnotes has been added in my plugin.

**Comment by pchr8** [comment]
@Comprehensive-Jason thank you, this is 10/10 what I wanted and works perfectly. Thank you so much!
