### ISSUE TITLE
[bug] Re-indexing not being saved

### ISSUE THREAD

**Issue by mayukhc** [akaalias/obsidian-footnotes#20]
Love the plugin, this feels like core functionality. Noticed a minor issue where auto re-indexing is working correctly in Reading View, but the indexing is reverted on LivePreview. 
For example, in live preview while editing
![Live_preview](https://user-images.githubusercontent.com/8831148/224889991-b43b3ebb-f639-4053-bbae-a0de7efd712e.png)
Reading Mode
![ReadingView](https://user-images.githubusercontent.com/8831148/224889996-5afc4525-3fee-459b-98aa-f1b5986c1b3b.png)
The indexing reverts back on entering edit mode again.

**Comment by Comprehensive-Jason** [comment]
This is an inherent property of how Obsidian renders Markdown footnotes. The footnote numbers it uses in Reading Mode are not in any way associated with the footnote numbers you input in Live Preview. 
The footnote numbers you input are only used to identify which footnotes match which footnote entries. Their numbers in reading mode are numbered in order of occurrence.

**Comment by mayukhc** [comment]
Good to know, closing this.
